package cat.rezelyn.watheextended.mixin.fix;

import cat.rezelyn.watheextended.api.config.hml.ConfigHelper;
import dev.doctor4t.wathe.api.Role;
import dev.doctor4t.wathe.api.WatheRoles;
import dev.doctor4t.wathe.cca.GameWorldComponent;
import dev.doctor4t.wathe.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.wathe.util.AnnounceWelcomePayload;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.util.Identifier;
import org.agmas.harpymodloader.Harpymodloader;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

// fix: any neutral-to-killer conversion assigning a disabled killer role
@Mixin(GameWorldComponent.class)
public abstract class DisabledKillerRoleConversionMixin {

    @Shadow
    public abstract void addRole(PlayerEntity player, Role role);

    @Shadow
    public abstract List<?> getAllKillerTeamPlayers();

    @Unique
    private static boolean watheextended$fixing = false;

    @Inject(method = "addRole(Lnet/minecraft/entity/player/PlayerEntity;Ldev/doctor4t/wathe/api/Role;)V", at = @At("RETURN"))
    private void watheextended$fixDisabledKillerConversion(PlayerEntity player, Role role, CallbackInfo ci) {
        if (watheextended$fixing) return;
        if (!role.canUseKiller()) return;

        Identifier id = role.identifier();
        if (id == null) return;

        List<String> disabled;
        try {
            disabled = ConfigHelper.getDisabledRoles();
        } catch (Throwable ignored) {
            return;
        }

        if (!disabled.contains(id.toString()) && !disabled.contains(id.getPath())) return;

        if (!(player instanceof ServerPlayerEntity serverPlayer)) return;

        List<Role> enabled = new ArrayList<>(WatheRoles.ROLES);
        enabled.removeIf(r -> {
            Identifier rid = r.identifier();
            return !r.canUseKiller() || rid == null || disabled.contains(rid.toString()) || disabled.contains(rid.getPath());
        });
        Collections.shuffle(enabled);
        Role replacement = enabled.isEmpty() ? WatheRoles.KILLER : enabled.getFirst();

        watheextended$fixing = true;
        try {
            addRole(player, replacement);
        } finally {
            watheextended$fixing = false;
        }

        try {
            int announcement = RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(Harpymodloader.autogeneratedAnnouncements.get(replacement));
            ServerPlayNetworking.send(serverPlayer, new AnnounceWelcomePayload(announcement, getAllKillerTeamPlayers().size(), 0));
        } catch (Throwable ignored) {
        }
    }
}
