package cat.rezelyn.watheextended.mixin.fix;

import dev.doctor4t.wathe.cca.GameWorldComponent;
import dev.doctor4t.wathe.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.wathe.game.GameFunctions;
import dev.doctor4t.wathe.index.WatheItems;
import dev.doctor4t.wathe.util.AnnounceWelcomePayload;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.util.Identifier;
import org.agmas.harpymodloader.Harpymodloader;
import org.agmas.harpymodloader.events.ModdedRoleAssigned;
import org.jetbrains.annotations.Nullable;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
import pro.fazeclan.river.stupid_express.constants.SERoles;

import java.util.List;

// fix: initiate not converting when other initiate is killed by a non-initiate
@Mixin(value = GameFunctions.class, priority = 800)
public class InitiateRemoteDeathMixin {

    @Inject(method = "killPlayer(Lnet/minecraft/entity/player/PlayerEntity;ZLnet/minecraft/entity/player/PlayerEntity;Lnet/minecraft/util/Identifier;)V", at = @At("HEAD"))
    private static void watheextended$convertInitiatePartner(PlayerEntity victim, boolean spawnBody, @Nullable PlayerEntity killer, Identifier deathReason, CallbackInfo ci) {
        if (!(victim instanceof ServerPlayerEntity serverVictim)) return;

        ServerWorld world = serverVictim.getServerWorld();
        GameWorldComponent game;
        try {
            game = GameWorldComponent.KEY.get(world);
        } catch (Throwable ignored) {
            return;
        }

        if (!game.isRunning() || !game.isRole(victim, SERoles.INITIATE)) return;

        boolean selfKill = killer == null || killer.getUuid().equals(victim.getUuid());
        // if killed by another Initiate (not self), let Stupid Express handle the conversion
        boolean killedByInitiate = !selfKill && game.isRole(killer, SERoles.INITIATE);
        if (killedByInitiate) return;

        List<ServerPlayerEntity> others = world.getPlayers(p -> game.isRole(p, SERoles.INITIATE) && !p.getUuid().equals(victim.getUuid()));
        for (ServerPlayerEntity player : others) {
            convertToAmnesiac(player, game);
        }

        if (selfKill) {
            convertToAmnesiac(serverVictim, game);
        }

        game.sync();
    }

    @Unique
    private static void convertToAmnesiac(ServerPlayerEntity player, GameWorldComponent game) {
        player.getInventory().removeOne(WatheItems.KNIFE.getDefaultStack());
        game.addRole(player, SERoles.AMNESIAC);
        ModdedRoleAssigned.EVENT.invoker().assignModdedRole(player, SERoles.AMNESIAC);

        try {
            int announcement = RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(Harpymodloader.autogeneratedAnnouncements.get(SERoles.AMNESIAC));
            ServerPlayNetworking.send(player, new AnnounceWelcomePayload(announcement, game.getAllKillerTeamPlayers().size(), 0));
        } catch (Throwable ignored) {
        }
    }
}
